# Generated by Django 2.2.2 on 2019-06-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Nome do plano')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor')),
            ],
        ),
    ]
